import {
  BitbucketIcon,
  BLockchainIcon,
  CeleryIcon,
  DatadogIcon,
  DjangoIcon,
  DockerIcon,
  FastAPIIcon,
  FlaskIcon,
  FoundryBookIcon,
  GithubIcon,
  GitlabIcon,
  GrafanaIcon,
  HardhatIcon,
  InfluxDBIcon,
  IOSAppIcon,
  MadeWithAIIcon,
  JavaScriptIcon,
  KubernetesIcon,
  NginxIcon,
  NodejsIcon,
  PostgreSQLIcon,
  PrometheusIcon,
  PythonIcon,
  PytorchIcon,
  RabbitMQIcon,
  ReactAppIcon,
  RedisIcon,
  RustIcon,
  SolidityIcon,
  TelegramIcon,
  TypescriptIcon,
} from "./icons";

export const serviceNameToIcon = {
  "Bitbucket Pipelines": <BitbucketIcon />,
  "Blockchain Indexer": <BLockchainIcon />,
  "The Graph": <BLockchainIcon />,
  C: "C",
  Celery: <CeleryIcon />,
  DataDog: <DatadogIcon />,
  Django: <DjangoIcon />,
  Docker: <DockerIcon />,
  FastAPI: <FastAPIIcon />,
  Flask: <FlaskIcon />,
  "Fluence Oracles": "Fluence Oracles",
  Foundry: <FoundryBookIcon />,
  "Github Actions": <GithubIcon />,
  "Gitlab CI&CD": <GitlabIcon />,
  Grafana: <GrafanaIcon />,
  Hardhat: <HardhatIcon />,
  JavaScript: <JavaScriptIcon />,
  K8s: <KubernetesIcon />,
  ML: <PytorchIcon />,
  Nginx: <NginxIcon />,
  "Node.js": <NodejsIcon />,
  PostgreSQL: <PostgreSQLIcon />,
  Prometheus: <PrometheusIcon />,
  Python: <PythonIcon />,
  RabbitMQ: <RabbitMQIcon />,
  ReactApp: <ReactAppIcon />,
  Redis: <RedisIcon />,
  Rust: <RustIcon />,
  "Rust Smart Contract": <RustIcon />,
  madeWithAI: <MadeWithAIIcon />,
  "Solidity Smart Contract": <SolidityIcon />,
  Solidity: <SolidityIcon />,
  TelegramBot: <TelegramIcon />,
  Truffle: "Truffle",
  TypeScript: <TypescriptIcon />,
  "iOS App": <IOSAppIcon />,
  InfluxDB: <InfluxDBIcon />,
};
