
name: Deploy to GitHub Pages 
permissions:
  contents: write
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Substitute JSON files from GitHub Secrets
      run: |
        echo "$EDUCATIONS_JSON" > src/dataAPIs/fixtures/educations.json
        echo "$PROJECTS_JSON" > src/dataAPIs/fixtures/projects.json
        echo "$WORKS_JSON" > src/dataAPIs/fixtures/works.json
      env:
        EDUCATIONS_JSON: ${{ secrets.EDUCATIONS_JSON }}
        PROJECTS_JSON: ${{ secrets.PROJECTS_JSON }}
        WORKS_JSON: ${{ secrets.WORKS_JSON }}
    
    - name: Substitute Prodcution Environment Variables
      run: |
        echo "REACT_APP_UMAMI_WEBSITE_ID=${{ vars.REACT_APP_UMAMI_WEBSITE_ID }}" > .env.production

    - name: Build the project
      run: CI=false && pnpm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build

